from typing import Any, Optional

from .editable import EditableMixin as EditableMixin
from .fullname import FullnameMixin as FullnameMixin
from .gildable import GildableMixin as GildableMixin
from .inboxable import InboxableMixin as InboxableMixin
from .inboxtoggleable import InboxToggleableMixin as InboxToggleableMixin
from .messageable import MessageableMixin as MessageableMixin
from .replyable import ReplyableMixin as ReplyableMixin
from .reportable import ReportableMixin as ReportableMixin
from .savable import SavableMixin as SavableMixin
from .votable import VotableMixin as VotableMixin


class ThingModerationMixin:
    REMOVAL_MESSAGE_API: Any = ...
    def approve(self) -> None: ...
    def distinguish(self, how: str = ..., sticky: bool = ...) -> None: ...
    def ignore_reports(self) -> None: ...
    def lock(self) -> None: ...
    def remove(self, spam: bool = ..., mod_note: str = ..., reason_id: Optional[Any] = ...) -> None: ...
    def send_removal_message(self, message: Any, title: str = ..., type: str = ...): ...
    def undistinguish(self) -> None: ...
    def unignore_reports(self) -> None: ...
    def unlock(self) -> None: ...

class UserContentMixin(EditableMixin, GildableMixin, InboxToggleableMixin, ReplyableMixin, ReportableMixin, SavableMixin, VotableMixin): ...
