from ....const import API_PATH as API_PATH

class InboxableMixin:
    def block(self) -> None: ...
    def collapse(self) -> None: ...
    def mark_read(self) -> None: ...
    def mark_unread(self) -> None: ...
    def uncollapse(self) -> None: ...
