from typing import Any

class VotableMixin:
    def _vote(self, direction: Any) -> None: ...
    def clear_vote(self) -> None: ...
    def downvote(self) -> None: ...
    def upvote(self) -> None: ...
