version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: quarterly
    labels:
      - "Dependencies"
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: quarterly
    labels:
      - "Dependencies"
