build:
  os: ubuntu-lts-latest
  tools:
    python: "3.14"
  jobs:
    install:
      - pip install uv
      - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --no-dev --group docs --link-mode=copy
formats:
  - htmlzip
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
version: 2
