build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
formats:
  - htmlzip
python:
  install:
    - method: pip
      extra_requirements:
        - readthedocs
      path: .
sphinx:
  configuration: docs/conf.py
version: 2
