from ..base import PRAWBase as PRAWBase
from typing import Any
from typing import Any

from ..base import PRAWBase as PRAWBase


class RedditBase(PRAWBase):
    @staticmethod
    def _url_parts(url: Any): ...
    def __eq__(self, other: Any) -> Any: ...
    def __getattr__(self, attribute: Any): ...
    def __hash__(self) -> Any: ...
    _fetched: bool = ...
    def __init__(self, reddit: Any, _data: Any) -> None: ...
    def __repr__(self): ...
    def __str__(self): ...
    def __ne__(self, other: Any) -> Any: ...
    def _fetch(self) -> None: ...
    def _reset_attributes(self, *attributes: Any) -> None: ...
