from ..base import PRAWBase as PRAWBase
from typing import Any
from typing import Any

from ..base import PRAWBase as PRAWBase


class RedditBase(PRAWBase):
    def __eq__(self, other: Any) -> Any: ...
    def __getattr__(self, attribute: Any): ...
    def __hash__(self) -> Any: ...
    def __init__(self, reddit: Any, _data: Any) -> None: ...
    def __ne__(self, other: Any) -> Any: ...
