from typing import Any, Optional
from typing import Dict, NoReturn, Generator

from .base import RedditBase as RedditBase
from .subreddit import Subreddit
from ...reddit import Reddit


class Emoji(RedditBase):
    STR_FIELD: str = ...
    name: str = ...
    url: str = ...
    def __eq__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...
    subreddit: Subreddit = ...
    def __init__(self, reddit: Reddit, subreddit: Subreddit, name: str, _data: Optional[Dict[str, Any]] = ...) -> Emoji: ...
    def delete(self) -> NoReturn: ...

class SubredditEmoji:
    def __getitem__(self, name: str) -> Emoji: ...
    subreddit: Subreddit = ...
    def __init__(self, subreddit: Subreddit) -> None: ...
    def __iter__(self) -> Generator[Emoji, None, None]: ...
    def add(self, name: str, image_path: str): ...
