from .base import RedditBase as RedditBase
from typing import Any, Optional
from typing import Any, Optional

from .base import RedditBase as RedditBase


class Emoji(RedditBase):
    STR_FIELD: str = ...
    def __eq__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...
    name: Any = ...
    subreddit: Any = ...
    def __init__(self, reddit: Any, subreddit: Any, name: Any, _data: Optional[Any] = ...) -> None: ...
    def delete(self) -> None: ...

class SubredditEmoji:
    def __getitem__(self, name: Any): ...
    subreddit: Any = ...
    def __init__(self, subreddit: Any) -> None: ...
    def __iter__(self) -> Any: ...
    def add(self, name: Any, image_path: Any): ...
