from ...const import API_PATH as API_PATH
from .base import RedditBase as RedditBase
from .mixins import FullnameMixin as FullnameMixin, InboxableMixin as InboxableMixin, ReplyableMixin as ReplyableMixin
from .redditor import Redditor as Redditor
from .subreddit import Subreddit as Subreddit
from typing import Any

class Message(InboxableMixin, ReplyableMixin, FullnameMixin, RedditBase):
    STR_FIELD: str = ...
    @classmethod
    def parse(cls, data: Any, reddit: Any): ...
    def __init__(self, reddit: Any, _data: Any) -> None: ...
    def delete(self) -> None: ...

class SubredditMessage(Message):
    def mute(self, _unmute: bool = ...) -> None: ...
    def unmute(self) -> None: ...
