from ..base import PRAWBase as PRAWBase
from typing import Any
from typing import Any

from ..base import PRAWBase as PRAWBase


class MoreComments(PRAWBase):
    count: Any = ...
    children: Any = ...
    _comments: Any = ...
    submission: Any = ...
    def __init__(self, reddit: Any, _data: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def __repr__(self): ...
    def _continue_comments(self, update: Any): ...
    def _load_comment(self, comment_id: Any): ...
    def comments(self, update: bool = ...): ...
