from ...const import API_PATH as API_PATH
from ..base import PRAWBase as PRAWBase
from typing import Any

class MoreComments(PRAWBase):
    count: Any = ...
    children: Any = ...
    submission: Any = ...
    def __init__(self, reddit: Any, _data: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def comments(self, update: bool = ...): ...
