from typing import Any

from ..base import PRAWBase as PRAWBase


class MoreComments(PRAWBase):
    count: Any = ...
    children: Any = ...
    submission: Any = ...
    def __init__(self, reddit: Any, _data: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def comments(self, update: bool = ...): ...
