from ...const import API_PATH as API_PATH
from ...util.cache import cachedproperty as cachedproperty
from ..listing.mixins import SubredditListingMixin as SubredditListingMixin
from .base import RedditBase as RedditBase
from .redditor import Redditor as Redditor
from .subreddit import Subreddit as Subreddit, SubredditStream as SubredditStream
from typing import Any, Optional

class Multireddit(SubredditListingMixin, RedditBase):
    STR_FIELD: str = ...
    RE_INVALID: Any = ...
    @staticmethod
    def sluggify(title: Any): ...
    def stream(self): ...
    path: Any = ...
    subreddits: Any = ...
    def __init__(self, reddit: Any, _data: Any) -> None: ...
    def add(self, subreddit: Any) -> None: ...
    def copy(self, display_name: Optional[Any] = ...): ...
    def delete(self) -> None: ...
    def remove(self, subreddit: Any) -> None: ...
    def update(self, **updated_settings: Any) -> None: ...
