from ..listing.mixins import SubredditListingMixin as SubredditListingMixin
from .base import RedditBase as RedditBase
from typing import Any, Optional
from typing import Any, Optional

from .base import RedditBase as RedditBase
from ..listing.mixins import SubredditListingMixin as SubredditListingMixin


class Multireddit(SubredditListingMixin, RedditBase):
    STR_FIELD: str = ...
    RE_INVALID: Any = ...
    @staticmethod
    def sluggify(title: Any): ...
    def stream(self): ...
    path: Any = ...
    subreddits: Any = ...
    def __init__(self, reddit: Any, _data: Any) -> None: ...
    def add(self, subreddit: Any) -> None: ...
    def copy(self, display_name: Optional[Any] = ...): ...
    def delete(self) -> None: ...
    def remove(self, subreddit: Any) -> None: ...
    def update(self, **updated_settings: Any) -> None: ...
