from ...const import API_PATH as API_PATH
from ...exceptions import ClientException as ClientException
from .base import RedditBase as RedditBase
from typing import Any, Optional

class RemovalReason(RedditBase):
    STR_FIELD: str = ...
    def __eq__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...
    id: Any = ...
    subreddit: Any = ...
    def __init__(self, reddit: Any, subreddit: Any, reason_id: Any, _data: Optional[Any] = ...) -> None: ...
    def delete(self) -> None: ...
    def update(self, message: Any, title: Any) -> None: ...

class SubredditRemovalReasons:
    def __getitem__(self, reason_id: Any): ...
    subreddit: Any = ...
    def __init__(self, subreddit: Any) -> None: ...
    def __iter__(self) -> Any: ...
    def add(self, message: Any, title: Any): ...
