body:
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    id: feature-description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      placeholder: Clear and concise description of any alternative solutions or features you've considered.
    id: alternatives-considered
  - type: textarea
    attributes:
      label: Additional context
      placeholder: Add any other context or links here.
    id: additional-context
description: Suggest an idea for this project
labels: ["Feature Request"]
name: Feature Request
