from .exceptions import ClientException as ClientException
from typing import Any

class _NotSet:
    def __bool__(self): ...
    __nonzero__: Any = ...

class Config:
    CONFIG: Any = ...
    CONFIG_NOT_SET: Any = ...
    LOCK: Any = ...
    @property
    def short_url(self): ...
    custom: Any = ...
    client_id: Any = ...
    reddit_url: Any = ...
    password: Any = ...
    def __init__(self, site_name: Any, **settings: Any) -> None: ...
