from configparser import RawConfigParser
from threading import Lock

from typing import Any, ClassVar, Dict, NoReturn, Optional, Union, TypeVar

_T = TypeVar("_T")

class Config:
    CONFIG: ClassVar[Optional[RawConfigParser]] = ...
    CONFIG_NOT_SET: ClassVar[_T] = ...
    LOCK: ClassVar[Lock] = ...

    @property
    def short_url(self) -> Union[str, _T]: ...

    custom: Dict[Union[str, Any], Union[str, Any]] = ...
    client_id: ClassVar[Optional[str]] = ...
    client_secret: ClassVar[Optional[str]] = ...
    oauth_url: ClassVar[Optional[str]] = ...
    reddit_url: ClassVar[Optional[str]] = ...
    refresh_token: ClassVar[Optional[str]] = ...
    redirect_uri: ClassVar[Optional[str]] = ...
    password: ClassVar[Optional[str]] = ...
    user_agent: ClassVar[Optional[str]] = ...
    username: ClassVar[Optional[str]] = ...

    def __init__(self, site_name: str, **settings: Union[str, Any]) -> NoReturn: ...
    check_for_updates: ClassVar[bool] = ...
    kinds: ClassVar[Dict[str, Any]] = ...
