from typing import ClassVar, NoReturn

class PRAWException(Exception): ...

class APIException(PRAWException):
    error_type: ClassVar[str] = ...
    message: ClassVar[str] = ...
    field: ClassVar[str] = ...
    def __init__(self, error_type: str, message: str, field: str) -> NoReturn: ...

class ClientException(PRAWException): ...
