from typing import Any

class PRAWException(Exception): ...

class APIException(PRAWException):
    error_type: Any = ...
    message: Any = ...
    field: Any = ...
    def __init__(self, error_type: Any, message: Any, field: Any) -> None: ...

class ClientException(PRAWException): ...
