from .exceptions import APIException as APIException, ClientException as ClientException
from .util import snake_case_keys as snake_case_keys
from typing import Any, Optional

class Objector:
    @classmethod
    def parse_error(cls, data: Any): ...
    @classmethod
    def check_error(cls, data: Any) -> None: ...
    parsers: Any = ...
    def __init__(self, reddit: Any, parsers: Optional[Any] = ...) -> None: ...
    def objectify(self, data: Any): ...
