from typing import Any, Optional

class Objector:
    @classmethod
    def parse_error(cls, data: Any): ...
    @classmethod
    def check_error(cls, data: Any) -> None: ...
    parsers: Any = ...
    _reddit: Any = ...
    def __init__(self, reddit: Any, parsers: Optional[Any] = ...) -> None: ...
    def _objectify_dict(self, data: Any): ...
    def objectify(self, data: Any): ...
