from . import models as models
from .config import Config as Config
from .const import API_PATH as API_PATH, USER_AGENT_FORMAT as USER_AGENT_FORMAT
from .exceptions import ClientException as ClientException
from .objector import Objector as Objector
from typing import Any, Optional

UPDATE_CHECKER_MISSING: bool

class Reddit:
    update_checked: bool = ...
    @property
    def read_only(self): ...
    @read_only.setter
    def read_only(self, value: Any) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *_args: Any) -> None: ...
    config: Any = ...
    auth: Any = ...
    front: Any = ...
    inbox: Any = ...
    live: Any = ...
    multireddit: Any = ...
    redditors: Any = ...
    subreddit: Any = ...
    subreddits: Any = ...
    user: Any = ...
    def __init__(self, site_name: Optional[Any] = ..., requestor_class: Optional[Any] = ..., requestor_kwargs: Optional[Any] = ..., **config_settings: Any) -> None: ...
    def comment(self, id: Optional[Any] = ..., url: Optional[Any] = ...): ...
    def domain(self, domain: Any): ...
    def get(self, path: Any, params: Optional[Any] = ...): ...
    def info(self, fullnames: Optional[Any] = ..., url: Optional[Any] = ...): ...
    def patch(self, path: Any, data: Optional[Any] = ...): ...
    def post(self, path: Any, data: Optional[Any] = ..., files: Optional[Any] = ..., params: Optional[Any] = ...): ...
    def put(self, path: Any, data: Optional[Any] = ...): ...
    def random_subreddit(self, nsfw: bool = ...): ...
    def redditor(self, name: Optional[Any] = ..., fullname: Optional[Any] = ...): ...
    def request(self, method: Any, path: Any, params: Optional[Any] = ..., data: Optional[Any] = ..., files: Optional[Any] = ...): ...
    def submission(self, id: Optional[Any] = ..., url: Optional[Any] = ...): ...
