from typing import Any, Optional, Callable


class cachedproperty:
    func: Any = ...
    __doc__: str = ...
    def __init__(self, func: Callable[[Any], Any], doc: Optional[str] = ...) -> None: ...
    def __get__(self, obj: Any, objtype: Optional[Any] = ...) -> Optional[Any]: ...
