from typing import Any, Optional

class cachedproperty:
    func: Any = ...
    __doc__: Any = ...
    def __init__(self, func: Any, doc: Optional[Any] = ...) -> None: ...
    def __get__(self, obj: Any, objtype: Optional[Any] = ...): ...
