from typing import Any, Optional, Dict
from typing import Generic, TypeVar

from ..base import PRAWBase as PRAWBase
from ...reddit import Reddit

T = TypeVar("T")


class ListingGenerator(PRAWBase, Generic[T]):
    limit: int = ...
    params: Dict[str, str] = ...
    url: str = ...
    yielded: int = ...
    def __init__(self, reddit: Reddit, url: str, limit: int = ..., params: Optional[Dict[str, str]] = ...) -> ListingGenerator: ...
    def __iter__(self) -> ListingGenerator: ...
    def __next__(self) -> Any: ...
