from ..base import PRAWBase as PRAWBase
from .listing import FlairListing as FlairListing
from typing import Any, Optional

class ListingGenerator(PRAWBase):
    limit: Any = ...
    params: Any = ...
    url: Any = ...
    yielded: int = ...
    def __init__(self, reddit: Any, url: Any, limit: int = ..., params: Optional[Any] = ...) -> None: ...
    def __iter__(self) -> Any: ...
    def __next__(self): ...
