from typing import Any, NoReturn, Optional, Generic, TypeVar

from ..base import PRAWBase as PRAWBase

T = TypeVar("T")

class Listing(PRAWBase, Generic[T]):
    CHILD_ATTRIBUTE: str = ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Any: ...
    def __setattr__(self, attribute: str, value: Any) -> NoReturn: ...

class FlairListing(Listing):
    CHILD_ATTRIBUTE: str = ...
    @property
    def after(self) -> Optional[Any]: ...
