from typing import Any, Set, Generator, Literal

from ...base import PRAWBase as PRAWBase


class BaseListingMixin(PRAWBase):
    VALID_TIME_FILTERS: Set[str] = ...
    def controversial(self, time_filter: Literal["all", "day", "hour", "month", "week", "year"] = ..., **generator_kwargs: str) -> Generator[Any]: ...
    def hot(self, **generator_kwargs: str) -> Generator[Any]: ...
    def new(self, **generator_kwargs: str) -> Generator[Any]: ...
    def top(self, time_filter: Literal["all", "day", "hour", "month", "week", "year"] = ..., **generator_kwargs: str) -> Generator[Any]: ...
