from typing import Any

from ...base import PRAWBase as PRAWBase


def _prepare(praw_object: Any, arguments_dict: Any, target: Any): ...

class BaseListingMixin(PRAWBase):
    VALID_TIME_FILTERS: Any = ...
    @staticmethod
    def _validate_time_filter(time_filter: Any) -> None: ...
    def controversial(self, time_filter: str = ..., **generator_kwargs: Any): ...
    def hot(self, **generator_kwargs: Any): ...
    def new(self, **generator_kwargs: Any): ...
    def top(self, time_filter: str = ..., **generator_kwargs: Any): ...
