from typing import Any

from ...base import PRAWBase as PRAWBase


class BaseListingMixin(PRAWBase):
    VALID_TIME_FILTERS: Any = ...
    def controversial(self, time_filter: str = ..., **generator_kwargs: Any): ...
    def hot(self, **generator_kwargs: Any): ...
    def new(self, **generator_kwargs: Any): ...
    def top(self, time_filter: str = ..., **generator_kwargs: Any): ...
