from .base import BaseListingMixin as BaseListingMixin
from .gilded import GildedListingMixin as GildedListingMixin
from typing import Any
from typing import Any

from .base import BaseListingMixin as BaseListingMixin
from .gilded import GildedListingMixin as GildedListingMixin


class RedditorListingMixin(BaseListingMixin, GildedListingMixin):
    def comments(self): ...
    def submissions(self): ...
    def downvoted(self, **generator_kwargs: Any): ...
    def gildings(self, **generator_kwargs: Any): ...
    def hidden(self, **generator_kwargs: Any): ...
    def saved(self, **generator_kwargs: Any): ...
    def upvoted(self, **generator_kwargs: Any): ...

class SubListing(BaseListingMixin):
    _listing_use_sort: bool = ...
    _reddit: Any = ...
    _path: Any = ...
    def __init__(self, reddit: Any, base_path: Any, subpath: Any) -> None: ...
