from typing import Any, Dict, Optional, List, Iterator, Union

from ..base import PRAWBase as PRAWBase
from ...reddit import Reddit


class BaseList(PRAWBase):
    CHILD_ATTRIBUTE: Optional[Union[List[Any], str]] = ...
    def __init__(self, reddit: Reddit, _data: Dict[str, Any]) -> BaseList: ...
    def __contains__(self, item: Any) -> bool: ...
    def __getitem__(self, index: int) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
