from typing import Any, Dict, NoReturn, Optional, List, Iterator

from ..base import PRAWBase as PRAWBase
from ...reddit import Reddit


class BaseList(PRAWBase):
    CHILD_ATTRIBUTE: Optional[List[Any]] = ...
    def __init__(self, reddit: Reddit, _data: Dict[str, Any]) -> NoReturn: ...
    def __contains__(self, item: Any) -> bool: ...
    def __getitem__(self, index: int) -> Any: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __len__(self) -> int: ...
