from typing import Any

from ..base import PRAWBase as PRAWBase


class BaseList(PRAWBase):
    CHILD_ATTRIBUTE: Any = ...
    def __init__(self, reddit: Any, _data: Any) -> None: ...
    def __contains__(self, item: Any): ...
    def __getitem__(self, index: Any): ...
    def __iter__(self) -> Any: ...
    def __len__(self): ...
    def __str__(self): ...
