from ..exceptions import ClientException as ClientException
from .base import PRAWBase as PRAWBase
from typing import Any

class Auth(PRAWBase):
    @property
    def limits(self): ...
    def authorize(self, code: Any): ...
    def implicit(self, access_token: Any, expires_in: Any, scope: Any) -> None: ...
    def scopes(self): ...
    def url(self, scopes: Any, state: Any, duration: str = ..., implicit: bool = ...): ...
