from .base import PRAWBase as PRAWBase
from typing import Optional, Union, Dict, Sequence, NoReturn, Set

from .base import PRAWBase as PRAWBase


class Auth(PRAWBase):
    @property
    def limits(self) -> Dict[str, Optional[Union[str, int]]]: ...
    def authorize(self, code: str) -> Optional[str]: ...
    def implicit(self, access_token: str, expires_in: int, scope: str) -> NoReturn: ...
    def scopes(self) -> Set[str]: ...
    def url(self, scopes: Sequence[str], state: str, duration: str = ..., implicit: bool = ...) -> str: ...
