from typing import Any

class PRAWBase:
    @staticmethod
    def _safely_add_arguments(argument_dict: Any, key: Any, **new_arguments: Any) -> None: ...
    @classmethod
    def parse(cls, data: Any, reddit: Any): ...
    _reddit: Any = ...
    def __init__(self, reddit: Any, _data: Any) -> None: ...
