from typing import Optional, List, Union

from .reddit.comment import Comment
from .reddit.more import MoreComments
from .reddit.submission import Submission


class CommentForest(List[Union[Comment, MoreComments]]):
    def __getitem__(self, index: int): ...
    def __init__(self, submission: Submission, comments: Optional[List[Comment]] = ...) -> CommentForest: ...
    def __len__(self) -> int: ...
    def list(self) -> List[Comment]: ...
    def replace_more(self, limit: int = ..., threshold: int = ...) -> List[MoreComments]: ...
