from .reddit.more import MoreComments as MoreComments
from typing import Any, Optional

class CommentForest:
    def __getitem__(self, index: Any): ...
    def __init__(self, submission: Any, comments: Optional[Any] = ...) -> None: ...
    def __len__(self): ...
    def list(self): ...
    def replace_more(self, limit: int = ..., threshold: int = ...): ...
