from typing import Any, Optional

class CommentForest:
    @staticmethod
    def _gather_more_comments(tree: Any, parent_tree: Optional[Any] = ...): ...
    def __getitem__(self, index: Any): ...
    _comments: Any = ...
    _submission: Any = ...
    def __init__(self, submission: Any, comments: Optional[Any] = ...) -> None: ...
    def __len__(self): ...
    def _insert_comment(self, comment: Any) -> None: ...
    def _update(self, comments: Any) -> None: ...
    def list(self): ...
    def replace_more(self, limit: int = ..., threshold: int = ...): ...
