from ..const import API_PATH as API_PATH
from .base import PRAWBase as PRAWBase
from .reddit.live import LiveThread as LiveThread
from .reddit.multi import Multireddit as Multireddit, Subreddit as Subreddit
from typing import Any, Optional

class LiveHelper(PRAWBase):
    def __call__(self, id: Any): ...
    def info(self, ids: Any): ...
    def create(self, title: Any, description: Optional[Any] = ..., nsfw: bool = ..., resources: Optional[Any] = ...): ...
    def now(self): ...

class MultiredditHelper(PRAWBase):
    def __call__(self, redditor: Any, name: Any): ...
    def create(self, display_name: Any, subreddits: Any, description_md: Optional[Any] = ..., icon_name: Optional[Any] = ..., key_color: Optional[Any] = ..., visibility: str = ..., weighting_scheme: str = ...): ...

class SubredditHelper(PRAWBase):
    def __call__(self, display_name: Any): ...
    def create(self, name: Any, title: Optional[Any] = ..., link_type: str = ..., subreddit_type: str = ..., wikimode: str = ..., **other_settings: Any): ...
