from ..const import API_PATH as API_PATH
from typing import Any

class Preferences:
    def __call__(self): ...
    def __init__(self, reddit: Any) -> None: ...
    def update(self, **preferences: Any): ...
