from ..const import API_PATH as API_PATH
from .base import PRAWBase as PRAWBase
from .listing.generator import ListingGenerator as ListingGenerator
from .util import stream_generator as stream_generator
from typing import Any

class Redditors(PRAWBase):
    def new(self, **generator_kwargs: Any): ...
    def popular(self, **generator_kwargs: Any): ...
    def search(self, query: Any, **generator_kwargs: Any): ...
    def stream(self, **stream_options: Any): ...
