from typing import Generator

from .base import PRAWBase as PRAWBase
from .reddit.redditor import Redditor
from .reddit.subreddit import Subreddit


class Redditors(PRAWBase):
    def new(self, **generator_kwargs: str) -> Generator[Subreddit]: ...
    def popular(self, **generator_kwargs: str) -> Generator[Subreddit]: ...
    def search(self, query: str, **generator_kwargs: str) -> Generator[Redditor]: ...
    def stream(self, **stream_options: str) -> Generator[Subreddit]: ...
