from typing import Any, Optional, List

from . import ListingGenerator
from .base import PRAWBase as PRAWBase
from .reddit.subreddit import Subreddit


class Subreddits(PRAWBase):
    def default(self, **generator_kwargs: str) -> ListingGenerator[Subreddit]: ...
    def gold(self, **generator_kwargs: str) -> ListingGenerator[Subreddit]: ...
    def new(self, **generator_kwargs: str) -> ListingGenerator[Subreddit]: ...
    def popular(self, **generator_kwargs: str) -> ListingGenerator[Subreddit]: ...
    def recommended(self, subreddits: List[Subreddit], omit_subreddits: Optional[List[Subreddit]] = ...) -> List[Subreddit]: ...
    def search(self, query: Any, **generator_kwargs: str) -> ListingGenerator[Subreddit]: ...
    def search_by_name(self, query: str, include_nsfw: bool = ..., exact: bool = ...) -> List[Subreddit]: ...
    def search_by_topic(self, query: str) -> List[Subreddit]: ...
    def stream(self, **stream_options: str) -> ListingGenerator[Subreddit]: ...
