from .base import PRAWBase as PRAWBase
from typing import Any, Optional
from typing import Any, Optional

from .base import PRAWBase as PRAWBase


class Subreddits(PRAWBase):
    def default(self, **generator_kwargs: Any): ...
    def gold(self, **generator_kwargs: Any): ...
    def new(self, **generator_kwargs: Any): ...
    def popular(self, **generator_kwargs: Any): ...
    def recommended(self, subreddits: Any, omit_subreddits: Optional[Any] = ...): ...
    def search(self, query: Any, **generator_kwargs: Any): ...
    def search_by_name(self, query: Any, include_nsfw: bool = ..., exact: bool = ...): ...
    def search_by_topic(self, query: Any): ...
    def stream(self, **stream_options: Any): ...
