from typing import Any, Dict, Optional

from .base import PRAWBase as PRAWBase
from ..reddit import Reddit


class Trophy(PRAWBase):
    award_id: Optional[str] = ...
    description: Optional[str] = ...
    icon_40: str = ...
    icon_70: str = ...
    name: str = ...
    url: Optional[str] = ...
    def __init__(self, reddit: Reddit, _data: Dict[str, Any]) -> Trophy: ...
