from typing import List, Generator, NoReturn, Union, Dict, Optional
from typing import List, Generator, NoReturn, Union, Dict, Optional

from .base import PRAWBase as PRAWBase
from .preferences import Preferences
from .reddit.multi import Multireddit
from .reddit.redditor import Redditor
from .reddit.subreddit import Subreddit
from ..reddit import Reddit


class User(PRAWBase):
    def preferences(self) -> Preferences: ...
    def __init__(self, reddit: Reddit) -> NoReturn: ...
    def blocked(self) -> List[Redditor]: ...
    def contributor_subreddits(self, **generator_kwargs: str) -> Generator[Subreddit]: ...
    def friends(self) -> List[Redditor]: ...
    def karma(self) -> Dict[Subreddit, Union[str, int, Any]]: ...
    def me(self, use_cache: bool = ...) -> Optional[Redditor]: ...
    def moderator_subreddits(self, **generator_kwargs: str) -> Generator[Subreddit]: ...
    def multireddits(self) -> List[Multireddit]: ...
    def subreddits(self, **generator_kwargs: str) -> Generator[Subreddit]: ...
