from typing import Any, Optional

class BoundedSet:
    max_items: Any = ...
    def __init__(self, max_items: Any) -> None: ...
    def __contains__(self, item: Any): ...
    def add(self, item: Any) -> None: ...

class ExponentialCounter:
    def __init__(self, max_counter: Any) -> None: ...
    def counter(self): ...
    def reset(self) -> None: ...

def permissions_string(permissions: Any, known_permissions: Any): ...
def stream_generator(function: Any, pause_after: Optional[Any] = ..., skip_existing: bool = ..., attribute_name: str = ..., **function_kwargs: Any) -> None: ...
