jobs:
  ci:
    name: CI
    secrets:
      NETWORK_TEST_CLIENT_ID: ${{ secrets.NETWORK_TEST_CLIENT_ID }}
      NETWORK_TEST_CLIENT_SECRET: ${{ secrets.NETWORK_TEST_CLIENT_SECRET }}
    uses: praw-dev/.github/.github/workflows/ci.yml@16645281204644e9e0e79c3b249b2472dff307a7 # v1.1.0
    with:
      package: praw
name: CI
on: [ pull_request, push ]
permissions: read-all
