concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    secrets:
      NETWORK_TEST_CLIENT_ID: ${{ secrets.NETWORK_TEST_CLIENT_ID }}
      NETWORK_TEST_CLIENT_SECRET: ${{ secrets.NETWORK_TEST_CLIENT_SECRET }}
    uses: praw-dev/.github/.github/workflows/ci.yml@9ff8957d0cab4cf8c9d7cb5592aedb3d456cc058 # v1.4.0
    with:
      min_python: "3.10"
      network_test: true
      python_versions: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
name: CI
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
permissions: read-all
