concurrency:
  group: check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: CI
    secrets:
      NETWORK_TEST_CLIENT_ID: ${{ secrets.NETWORK_TEST_CLIENT_ID }}
      NETWORK_TEST_CLIENT_SECRET: ${{ secrets.NETWORK_TEST_CLIENT_SECRET }}
    uses: praw-dev/.github/.github/workflows/ci.yml@1d4a4eb39290407d05b4c8fb0a7ec36fb9ff935d # v1.3.2
    with:
      min_python: "3.10"
      network_test: true
      python_versions: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
name: CI
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
permissions: read-all
