jobs:
  dependabot_automerge:
    name: Dependabot automerge
    permissions:
      contents: write # required to merge the pull request
      pull-requests: write # required to enable auto-merge on the pull request
    uses: praw-dev/.github/.github/workflows/dependabot_automerge.yml@34032c07a7e2f432e0bb13ff126ed667d96e2528 # v1.8.0
name: Dependabot automerge
on:
  pull_request:
permissions: {}
