jobs:
  dependabot_automerge:
    name: Dependabot automerge
    permissions:
      pull-requests: read # required by fetch-metadata; the merge uses an app token
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    uses: praw-dev/.github/.github/workflows/dependabot_automerge.yml@ec52651e5b4e1de96c58ed3652e662588fb62dbb # v1.9.0
name: Dependabot automerge
on:
  pull_request:
permissions: {}
