concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint workflows
    permissions:
      contents: read # required to check out the repository
    uses: praw-dev/.github/.github/workflows/lint.yml@97050199f9773073e4360d798053b7fb342e4c1f # v1.11.0
name: Lint workflows
on:
  pull_request:
  push:
    branches: ["main"]
permissions: {}
