concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint workflows
    permissions:
      contents: read # required to check out the repository
    uses: praw-dev/.github/.github/workflows/lint.yml@ec52651e5b4e1de96c58ed3652e662588fb62dbb # v1.9.0
name: Lint workflows
on:
  pull_request:
  push:
    branches: ["main"]
permissions: {}
