concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint workflows
    permissions:
      contents: read # required to check out the repository
    uses: praw-dev/.github/.github/workflows/lint.yml@34032c07a7e2f432e0bb13ff126ed667d96e2528 # v1.8.0
name: Lint workflows
on:
  pull_request:
  push:
    branches: ["main"]
permissions: {}
