jobs:
  pre-commit_autoupdate:
    name: Update pre-commit hooks
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    uses: praw-dev/.github/.github/workflows/pre-commit_autoupdate.yml@e86d5e7389cc00472a01675465bfa72b1dffd884 # v1.2.0
name: Update pre-commit hooks
on:
  schedule:
    - cron: 0 15 * * 1
  workflow_dispatch:
permissions:
  contents: read
