jobs:
  pre-commit_autoupdate:
    name: Update pre-commit hooks
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    uses: praw-dev/.github/.github/workflows/pre-commit_autoupdate.yml@ec3a733628adc5bd596def5294dae9fb4eb1e501 # v1.6.0
name: Update pre-commit hooks
on:
  schedule:
    - cron: 0 15 * * 1
  workflow_dispatch:
permissions:
  contents: read
