jobs:
  pre-commit_autoupdate:
    name: Update pre-commit hooks
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    uses: praw-dev/.github/.github/workflows/pre-commit_autoupdate.yml@16645281204644e9e0e79c3b249b2472dff307a7 # v1.1.0
name: Update pre-commit hooks
on:
  schedule:
    - cron: 0 15 * * 1
  workflow_dispatch:
permissions:
  contents: read
