jobs:
  prepare_release:
    name: Prepare Release
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    uses: praw-dev/.github/.github/workflows/prepare_release.yml@1d4a4eb39290407d05b4c8fb0a7ec36fb9ff935d # v1.3.2
    with:
      package: praw
      version: ${{ inputs.version }}
      version_file: const.py
name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to prepare for release
        required: true
permissions:
  contents: read
