jobs:
  prepare_release:
    name: Prepare Release
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    uses: praw-dev/.github/.github/workflows/prepare_release.yml@d00355f9d670fa915fd5cd4f0ac422061951f55a # v1.3.1
    with:
      package: praw
      version: ${{ inputs.version }}
      version_file: const.py
name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to prepare for release
        required: true
permissions:
  contents: read
