jobs:
  prepare_release:
    name: Prepare Release
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
    uses: praw-dev/.github/.github/workflows/prepare_release.yml@aa63811572338b6343772c542574909f1cbd8d78 # v1.5.0
    with:
      package: praw
      version: ${{ inputs.version }}
      version_file: const.py
name: Prepare Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to prepare for release
        required: true
permissions:
  contents: read
