jobs:
  stale_action:
    name: Close stale issues and PRs
    uses: praw-dev/.github/.github/workflows/stale_action.yml@16645281204644e9e0e79c3b249b2472dff307a7 # v1.1.0
name: Close stale issues and PRs
on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:
permissions:
  issues: write
  pull-requests: write
