jobs:
  stale_action:
    name: Close stale issues and PRs
    uses: praw-dev/.github/.github/workflows/stale_action.yml@e86d5e7389cc00472a01675465bfa72b1dffd884 # v1.2.0
name: Close stale issues and PRs
on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:
permissions:
  issues: write
  pull-requests: write
