jobs:
  stale_action:
    name: Close stale issues and PRs
    secrets: inherit
    uses: praw-dev/.github/.github/workflows/stale_action.yml@f33b50e54733ad51138f0568b95552963d47b4a3 # v1.0.0
name: Close stale issues and PRs
on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:
permissions:
  issues: write
  pull-requests: write
