jobs:
  tag_release:
    name: Tag Release
    uses: praw-dev/.github/.github/workflows/tag_release.yml@20f00d1404e64813b40e0cff3a70dc9cd8b8b34e # v1.3.3
name: Tag Release
on:
  push:
    branches: [ main, release_test ]
permissions:
  contents: write
