jobs:
  tag_release:
    name: Tag Release
    uses: praw-dev/.github/.github/workflows/tag_release.yml@f33b50e54733ad51138f0568b95552963d47b4a3 # v1.0.0
name: Tag Release
on:
  push:
    branches: [ main, release_test ]
permissions:
  contents: write
