jobs:
  tag_release:
    name: Tag Release
    uses: praw-dev/.github/.github/workflows/tag_release.yml@d00355f9d670fa915fd5cd4f0ac422061951f55a # v1.3.1
name: Tag Release
on:
  push:
    branches: [ main, release_test ]
permissions:
  contents: write
