jobs:
  release_tag:
    if: "startsWith(github.event.head_commit.message, 'Merge pull request #') && contains(github.event.head_commit.message, ' from praw-dev/prepare_release_v')"
    name: "Tag Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
      run: |
        git checkout HEAD^2^
        git show
name: Prepare Release
on:
  push:
    branches:
      - release_test

